server:
  port: 5003

spring:
  application:
    name: SUBMISSION-SERVICE

#    spring.jpa.hibernate.ddl-auto=update
#    spring.datasource.url=jdbc:mysql://localhost:3306/mydatabase
#    spring.datasource.username=myuser
#    spring.datasource.password=secret
#    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#    spring.jpa.show-sql: true
  jpa:
      hibernate:
        ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/submission_service
    username: root
    password: shukla@791
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/